version: '3'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    image: sisgep
    container_name: sisgep
    ports:
      - "8080:80"
    volumes:
      - ./app/src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: banco
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: meu_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1